### ISSUE TITLE
[Request] Ability to add discounts on requisitions

### ISSUE THREAD

**Issue by VVoruganti** [HackGT/piranha#221] opened 2021-01-24 18:24 UTC
There are some instances where we order items in bulk or negotiate with vendors to receive a discount on top of the total order. So for complicated orders with many line items. It would be very useful to be able to have a final option to put a percentage or flat discount to the total order.

**Comment by evan10s** [comment] 2021-01-24 19:08
Duplicate of #216, i'll move this there

**Closed by evan10s** 2021-01-24 19:08 UTC
Labels: enhancement
